export { CAP } from "./utils/capabilities"
export type { OperationsCapability } from "./utils/capabilities"
export { can, canForOutlet, canViewOutletList } from "./utils/resolver"
export { authorizationErrorMessage } from "./utils/authorization-error"
export { useAuthorization } from "./hooks/use-authorization"
export { OutletCapabilityGuard, RequireCapability } from "./components/authorization-guard"
