export { CAP } from "./utils/capabilities"
export type { OperationsCapability } from "./utils/capabilities"
export { can, canForOutlet, canViewOutletList, isMerchantOwner, roleForOutlet } from "./utils/resolver"
export { authorizationErrorMessage } from "./utils/authorization-error"
export { useAuthorization } from "./hooks/use-authorization"
export { useOutletAuthorization } from "./hooks/use-outlet-authorization"
export { OutletCapabilityGuard, RequireCapability, RequireOwner } from "./components/authorization-guard"
